--- # Install and start HTTPD
- hosts: elanlab
  user: ansible
  sudo: yes
  gather_facts: no
  vars_files: 
    - conf/webdefaults.yml
  tasks:
   - name: Install HTTPD
     yum: name=httpd state=latest
   - name: Start Service
     service: name=httpd state=started
   - name: verify service is running
     command: service httpd status
     register: result
   - name: Install {{ pkg_lynx}} Web browser
     yum: name={{ pkg_lynx}} state=installed
   - debug: var=result
