--- # My first playbook
- hosts: webserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache HTTPD
      action: yum name=httpd state=installed
      notify: Restart HTTPD
  handlers: 
    - name: Restart HTTPD
      action: service name=httpd state=restarted
