--- # Example playbook for tags
- hosts: debian
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Install telnet and lynx packages
     yum: pkg={{ item }} state=latest
     with_items:
      - telnet
      - lynx
     tags:
      - install
   - name: start services
     service: name=ntp state=started
     tags:
       - servicestart
